### ISSUE TITLE
Undefined index: OU Attestation/AttestationOjbect.php

### ISSUE THREAD

**Issue by matteopuppis** [lbuchs/WebAuthn#36] opened 2021-06-08 12:04 UTC
Undefined index in these functions when opening from mobile browser

public function getCertificateIssuer()
    {
        $pem = $this->getCertificatePem();
        $issuer = '';
        if ($pem) {
            $certInfo = \openssl_x509_parse($pem);
            if (\is_array($certInfo) && \is_array($certInfo['issuer'])) {
                if ($certInfo['issuer']['CN']) {
                    $issuer .= \trim($certInfo['issuer']['CN']);
                }
                if ($certInfo['issuer']['O'] || $certInfo['issuer']['OU']) {
                   
                    if ($issuer) {
                        $issuer .= ' (' . \trim($certInfo['issuer']['O'] . ' ' . $certInfo['issuer']['OU']) . ')';
                    } else {
                        $issuer .= \trim($certInfo['issuer']['O'] . ' ' . $certInfo['issuer']['OU']);
                    }
                }
            }
        }

        return $issuer;
    }

    /**
     * return the certificate subject as string
     * @return string
     */
    public function getCertificateSubject()
    {
        $pem = $this->getCertificatePem();
        $subject = '';
        if ($pem) {
            $certInfo = \openssl_x509_parse($pem);
            if (\is_array($certInfo) && \is_array($certInfo['subject'])) {
                if ($certInfo['subject']['CN']) {
                    $subject .= \trim($certInfo['subject']['CN']);
                }
                if ($certInfo['subject']['O'] || $certInfo['subject']['OU']) {
                    
                    if ($subject) {
                        $subject .= ' (' . \trim($certInfo['subject']['O'] . ' ' . $certInfo['subject']['OU']) . ')';
                    } else {
                        $subject .= \trim($certInfo['subject']['O'] . ' ' . $certInfo['subject']['OU']);
                    }
                }
            }
        }

        return $subject;
    }

**Comment by matteopuppis** [comment] 2021-06-08 12:05
I solved it by adding in the first function

```
if (empty($certInfo['issuer']['OU'])) {
                        $certInfo['issuer']['OU'] = '';
                    }
```
and in the second
if (empty($certInfo['subject']['OU'])) {
                        $certInfo['subject']['OU'] = '';
                    }

**Comment by lbuchs** [comment] 2021-06-08 12:08
duplicate of #13

**Closed by lbuchs** 2021-06-08 12:08 UTC
