### ISSUE TITLE
PHP error AttestationObject.php line 90

### ISSUE THREAD

**Issue by wagner-robert** [lbuchs/WebAuthn#46] opened 2021-09-30 14:29 UTC
I am getting PHP errors in AttestationObject.php line 90 for YubiKey.
Undefined Index: OU
Undefined Index: O
Line: if ($certInfo['issuer']['O'] ||  $certInfo['issuer']['OU'])  {....

This appears to be looking for the O and OU in the Issuer field.  However, this YubiKey shows:

Issuer: CN=Yubico U2F Root CA Serial ...

There isn't a O or OU in the Issuer field.  Only in the Subject Field.

**Comment by wagner-robert** [comment] 2021-09-30 14:58
https://gitmemory.com/issue/lbuchs/WebAuthn/36/856706312  

I solved it by adding in the first function

if (empty($certInfo['issuer']['OU'])) {
                        $certInfo['issuer']['OU'] = '';
                    }

and in the second

if (empty($certInfo['subject']['OU'])) {
                        $certInfo['subject']['OU'] = '';
                    }

**Comment by lbuchs** [comment] 2021-10-04 15:27
duplicate of #13

**Closed by lbuchs** 2021-10-04 15:27 UTC
