### ISSUE TITLE
update packagist

### ISSUE THREAD

**Issue by MordiSacks** [lbuchs/WebAuthn#75] opened 2023-05-16 07:08 UTC
It looks like this package is not auto updated on Packagist
on github the latest tag is 2.0.0 but on packagist it's 2.0.0-beta
https://packagist.org/packages/lbuchs/webauthn

**Comment by lbuchs** [comment] 2023-05-16 07:12
duplicate of #67 , check me response there.

**Closed by lbuchs** 2023-05-16 07:12 UTC

**Comment by MordiSacks** [comment] 2023-05-16 07:14
Thank you, OMG this is ridicules, I just updated it.
