### ISSUE TITLE
ByteBuffer incompatible with PHP 8.1

### ISSUE THREAD

**Issue by brainfoolong** [lbuchs/WebAuthn#52] opened 2021-11-29 06:57 UTC
Hi!

The ByteBuffer class is incompatible with PHP 8.1

I had to remove \Serializable interface (https://php.watch/versions/8.1/serializable-deprecated) and also to fix the return type of `jsonSerialize` to `:mixed`.

I don't create a pull request for this, as i guess this is a breaking change for existing users.

**Comment by lbuchs** [comment] 2021-11-29 08:48
duplicate of #37

**Closed by lbuchs** 2021-11-29 08:48 UTC
