### ISSUE TITLE
invalid attestation format

### ISSUE THREAD

**Issue by redochka** [lbuchs/WebAuthn#1] opened 2019-03-07 18:07 UTC
Hello,
Just tried https://webauthn.lubu.ch/_test/client.html on my Android 8.1 chrome 72.0.3626.121 and i am having this error once the fingerprint verification succeeds:

`invalid attestation format`

**Comment by JohannesRegner** [comment] 2019-04-05 06:27
Same here, Mac OS with Chrome and Hypersecu Key...

**Comment by lbuchs** [comment] 2019-04-05 16:49
this should be fixed now (added attestation format 'packed' and 'android-key'). The android-safetynet attestation format which is used for fingerprints by Google Chrome mobile is still not supported.

**Comment by JohannesRegner** [comment] 2019-04-08 13:28
Ive tested it, the key works on your example, but not on my server...?! The problem is that, in AttestantionObject.php the variable $enc['fmt'] = null ...

**Closed** 2019-04-08 14:55 UTC

**Comment by redochka** [comment] 2019-04-26 15:37
Great, it is working here on Google Chrome mobile with android-safetynet.
I have been able to use the fingerprint authentication.
Cheers
